# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/mblaze/mblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze || ORIG_REF_NAME==mblaze}]

# IP: bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_0 || ORIG_REF_NAME==mblaze_microblaze_0_0}]

# IP: bd/mblaze/ip/mblaze_dlmb_v10_0/mblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_dlmb_v10_0 || ORIG_REF_NAME==mblaze_dlmb_v10_0}]

# IP: bd/mblaze/ip/mblaze_ilmb_v10_0/mblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_ilmb_v10_0 || ORIG_REF_NAME==mblaze_ilmb_v10_0}]

# IP: bd/mblaze/ip/mblaze_dlmb_bram_if_cntlr_0/mblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_dlmb_bram_if_cntlr_0}]

# IP: bd/mblaze/ip/mblaze_ilmb_bram_if_cntlr_0/mblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_ilmb_bram_if_cntlr_0}]

# IP: bd/mblaze/ip/mblaze_lmb_bram_0/mblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_lmb_bram_0 || ORIG_REF_NAME==mblaze_lmb_bram_0}]

# IP: bd/mblaze/ip/mblaze_microblaze_0_axi_periph_0/mblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mblaze_microblaze_0_axi_periph_0}]

# IP: bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_microblaze_0_axi_intc_0}]

# IP: bd/mblaze/ip/mblaze_microblaze_0_xlconcat_0/mblaze_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mblaze_microblaze_0_xlconcat_0}]

# IP: bd/mblaze/ip/mblaze_mdm_1_0/mblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_mdm_1_0 || ORIG_REF_NAME==mblaze_mdm_1_0}]

# IP: bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_clk_wiz_1_0 || ORIG_REF_NAME==mblaze_clk_wiz_1_0}]

# IP: bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mblaze_rst_clk_wiz_1_100M_0}]

# IP: bd/mblaze/ip/mblaze_axi_mem_intercon_0/mblaze_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_axi_mem_intercon_0 || ORIG_REF_NAME==mblaze_axi_mem_intercon_0}]

# IP: bd/mblaze/ip/mblaze_xbar_0/mblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_xbar_0 || ORIG_REF_NAME==mblaze_xbar_0}]

# IP: bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_mig_7series_0_1 || ORIG_REF_NAME==mblaze_mig_7series_0_1}]

# IP: bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==mblaze_rst_mig_7series_0_81M_1}]

# IP: bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_axi_uartlite_0_0}]

# IP: bd/mblaze/ip/mblaze_xbar_1/mblaze_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_xbar_1 || ORIG_REF_NAME==mblaze_xbar_1}]

# IP: bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_axi_gpio_0_0}]

# IP: bd/mblaze/ip/mblaze_axi_timer_0_0/mblaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_axi_timer_0_0 || ORIG_REF_NAME==mblaze_axi_timer_0_0}]

# IP: bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_axi_ethernetlite_0_0 || ORIG_REF_NAME==mblaze_axi_ethernetlite_0_0}]

# IP: bd/mblaze/ip/mblaze_mii_to_rmii_0_0/mblaze_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_mii_to_rmii_0_0 || ORIG_REF_NAME==mblaze_mii_to_rmii_0_0}]

# IP: bd/mblaze/ip/mblaze_auto_cc_0/mblaze_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_auto_cc_0 || ORIG_REF_NAME==mblaze_auto_cc_0}]

# IP: bd/mblaze/ip/mblaze_auto_us_0/mblaze_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_auto_us_0 || ORIG_REF_NAME==mblaze_auto_us_0}]

# IP: bd/mblaze/ip/mblaze_auto_us_1/mblaze_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_auto_us_1 || ORIG_REF_NAME==mblaze_auto_us_1}]

# XDC: bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_0 || ORIG_REF_NAME==mblaze_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_dlmb_v10_0/mblaze_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_dlmb_v10_0 || ORIG_REF_NAME==mblaze_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_dlmb_v10_0/mblaze_dlmb_v10_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_ilmb_v10_0/mblaze_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_ilmb_v10_0 || ORIG_REF_NAME==mblaze_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_ilmb_v10_0/mblaze_ilmb_v10_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_dlmb_bram_if_cntlr_0/mblaze_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_ilmb_bram_if_cntlr_0/mblaze_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_lmb_bram_0/mblaze_lmb_bram_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_mdm_1_0/mblaze_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_mdm_1_0 || ORIG_REF_NAME==mblaze_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_mdm_1_0/mblaze_mdm_1_0_ooc_trace.xdc

# XDC: bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_clk_wiz_1_0 || ORIG_REF_NAME==mblaze_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_clk_wiz_1_0 || ORIG_REF_NAME==mblaze_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mblaze_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mblaze_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_xbar_0/mblaze_xbar_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1/user_design/constraints/mblaze_mig_7series_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_mig_7series_0_1 || ORIG_REF_NAME==mblaze_mig_7series_0_1}]

# XDC: bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1/user_design/constraints/mblaze_mig_7series_0_1_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_mig_7series_0_1 || ORIG_REF_NAME==mblaze_mig_7series_0_1}]

# XDC: bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==mblaze_rst_mig_7series_0_81M_1}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==mblaze_rst_mig_7series_0_81M_1}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_xbar_1/mblaze_xbar_1_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_timer_0_0/mblaze_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_timer_0_0 || ORIG_REF_NAME==mblaze_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_timer_0_0/mblaze_axi_timer_0_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_ethernetlite_0_0 || ORIG_REF_NAME==mblaze_axi_ethernetlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_ethernetlite_0_0 || ORIG_REF_NAME==mblaze_axi_ethernetlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_axi_ethernetlite_0_0 || ORIG_REF_NAME==mblaze_axi_ethernetlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_mii_to_rmii_0_0/mblaze_mii_to_rmii_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_mii_to_rmii_0_0 || ORIG_REF_NAME==mblaze_mii_to_rmii_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mblaze/ip/mblaze_mii_to_rmii_0_0/mblaze_mii_to_rmii_0_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_auto_cc_0/mblaze_auto_cc_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_auto_cc_0/mblaze_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_auto_cc_0 || ORIG_REF_NAME==mblaze_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/mblaze/ip/mblaze_auto_us_0/mblaze_auto_us_0_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_auto_us_0/mblaze_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_auto_us_0 || ORIG_REF_NAME==mblaze_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/mblaze/ip/mblaze_auto_us_1/mblaze_auto_us_1_ooc.xdc

# XDC: bd/mblaze/ip/mblaze_auto_us_1/mblaze_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mblaze_auto_us_1 || ORIG_REF_NAME==mblaze_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/mblaze/mblaze_ooc.xdc
