# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.cache/wt [current_project]
set_property parent.project_path C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/mblaze.bd
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_microblaze_0_0/mblaze_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_dlmb_v10_0/mblaze_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_dlmb_v10_0/mblaze_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_ilmb_v10_0/mblaze_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_ilmb_v10_0/mblaze_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_dlmb_bram_if_cntlr_0/mblaze_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_ilmb_bram_if_cntlr_0/mblaze_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_lmb_bram_0/mblaze_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_microblaze_0_axi_intc_0/mblaze_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mdm_1_0/mblaze_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mdm_1_0/mblaze_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_clk_wiz_1_0/mblaze_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_rst_clk_wiz_1_100M_0/mblaze_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_xbar_0/mblaze_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1/user_design/constraints/mblaze_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1/user_design/constraints/mblaze_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mig_7series_0_1/mblaze_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_rst_mig_7series_0_81M_1/mblaze_rst_mig_7series_0_81M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_uartlite_0_0/mblaze_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_xbar_1/mblaze_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_gpio_0_0/mblaze_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_timer_0_0/mblaze_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_timer_0_0/mblaze_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_axi_ethernetlite_0_0/mblaze_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mii_to_rmii_0_0/mblaze_mii_to_rmii_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_mii_to_rmii_0_0/mblaze_mii_to_rmii_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_auto_cc_0/mblaze_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_auto_cc_0/mblaze_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_auto_us_0/mblaze_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_auto_us_0/mblaze_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_auto_us_1/mblaze_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/ip/mblaze_auto_us_1/mblaze_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/mblaze_ooc.xdc]
set_property is_locked true [get_files C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/mblaze.bd]

read_vhdl -library xil_defaultlib C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/sources_1/bd/mblaze/hdl/mblaze_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files C:/Users/senel/micro_blaze.xpr/proje_2016/proje_2016.srcs/constrs_1/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mblaze_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mblaze_wrapper.dcp

catch { report_utilization -file mblaze_wrapper_utilization_synth.rpt -pb mblaze_wrapper_utilization_synth.pb }
